### ISSUE TITLE
Container is empty and can't scroll through my hotbar

### ISSUE THREAD

**Issue by TheMythcaller** [ldtteam/BlockUI#11]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: 1.17.1-1.0.43-ALPHA
- Structurize Version: 1.17.1-0.13.253-ALPHA
- Related Mods and their Versions:
- Domum Ornamentum Version: 1.17.1-1.0.10-ALPHA
- Block UI/ UI Library Mod Version: 1.17.1-0.0.26-ALPHA
- Multi-Piston Version: 1.17.1-1.2.1-ALPHA

## Expected behavior
I would be able to look at a chest or other container and scroll through my Hotbar at the same time.

## Actual behavior
When I look at a chest or other container just right a message appears over it saying "This Container is Empty" and while looking at the chest while within interacting distance I am unable to scroll through my Hotbar. If the container has things in it, the message doesn't appear and when I look at the chest and/or crouch while looking at the chest a message in chat states "OpenGL Error: 1281 (Invalid value). 

![2021-10-13_20 29 56](https://user-images.githubusercontent.com/92497143/137244684-32480a57-927f-41e2-aead-a8e091a96b9c.png)
![2021-10-13_21 22 16](https://user-images.githubusercontent.com/92497143/137245845-b62ed30f-7136-4666-baf6-18ab9bdab843.png)

## Steps to reproduce the issue

1. Create a New World.
2. Place a Chest or other container.
3. Look at the container while within interaction distance and try to scroll through your hotbar.

### Logs

- latest.log: https://gist.github.com/TheMythcaller/e01e6d8e44b4c0bfede4e8575bee06a6
- crashlog: Didn't cause a crash.

### Notes
Ignore the other mods, I recreated the issue with only Minecolonies and its dependencies installed.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
This is dev test and shouldn't load in normal game, whoopsie

**Comment by TheMythcaller** [comment]
> This is dev test and shouldn't load in normal game, whoopsie

With the new Alpha version it is still there

**Comment by Sindenky** [comment]
I would like to piggy-back on this. 
Version: blockui-1.17.1-0.0.26-ALPHA
Any vanilla inventory (chest, hopper, dispenser, ect.) locks the scroll wheel when looking at them.

**Comment by Nightenom** [comment]
Can you try the newest 0.0.31?
<https://www.curseforge.com/minecraft/mc-mods/blockui/files/3542268>

**Comment by Sindenky** [comment]
I'll push for an update and report back with our findings.

**Comment by Sindenky** [comment]
Updated
Version: blockui-1.17.1-0.0.31-ALPHA

Issue is fixed. Thank you so much!
