### ISSUE TITLE
Crash when opening recipe book with minecolonies loaded

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/BlockUI#12]
Minecraft version 1.17
Using Minecolonies 1.0.27-Alpha (and confirmed with minecolonies 1.0.56)
Using Block-UI 0.0.26-Alpha
Using Forge 1.0.85

In forge 1.0.85, tooltips changed. From this forge version onwards, minecraft crashes when the recipe book is opened and you have a build tool and wooden planks in your inventory, and just minecolonies and its dependencies are loaded.

Crash log: https://gist.github.com/MotionlessTrain/9d1bf7be909dd8f2ab095b869c8f5223

By removing mods, it turned out this didn't happen with just the dependency mods loaded. When minecolonies was added as well, it started to crash.

I asked Ray on stream where I should post the crash log, and he pointed me to here.

**Comment by Nightenom** [comment]
Not blockui problem, usually problem of item owner (item mod)

**Comment by MotionlessTrain** [comment]
I'll post it on the minecolonies issue tracker then

**Comment by Raycoms** [comment]
No, not related to MineColonies.

**Comment by MotionlessTrain** [comment]
You are completely right. I just reproduced it with just forge 37.0.85 (and no mods installed)
