### ISSUE TITLE
[bug] Project MMO Cannot Detect Interface is Active

### ISSUE THREAD

**Issue by SomewhatDamaged** [ldtteam/BlockUI#43]
**Describe the bug**
Block-picking interfaces in huts are having an interaction with Project MMO.

Trying to type into the (for example) Minimum Stock text field, and starting the string with a P, opens the Project MMO interface. 

This seems to be a case of PMMO needing to action its interface whenever there is a tooltip visible and those specific interfaces having tooltips.

![image](https://github.com/ldtteam/BlockUI/assets/6394544/c3972186-1758-482a-9f97-296fdeb7f520)

**Expected behavior**
Pressing the interface key for PMMO should not cause it to come up.

**To Reproduce**
1. Open builder hut interface
2. Select `Minimum Stock` and click `Add`
3. In the provided text box, try to type `Pickaxe`
4. The Project MMO interface will pop up

**Versions:**
Minecraft: 1.20.1
Forge: 47.1.0
BlockUI: 1.20.1-0.0.84
Domum Ornamentum: 1.20.1-1.0.104
Multipiston: 1.20.1-1.2.31
Minecolonies: 1.20.1-1.1.9
[Project MMO: 1.20.1-1.0.2](https://www.curseforge.com/minecraft/mc-mods/project-mmo)

**Additional context**
Additional information from the PMMO mod developer: https://github.com/Caltinor/Project-MMO-2.0/issues/324

**Comment by Raycoms** [comment]
We do set the screen accordingly, but we also do display the forge tooltip yes. I am not sure what we could do on our side to prevent that.

**Comment by SomewhatDamaged** [comment]
Yeah. Fair enough. Was hoping there might be something checkable when a BlockUI interface was up, that PMMO could use to avoid interrupting those interfaces.

**Comment by Raycoms** [comment]
They can add a runtime dependency and check if the ui is one of ours. Not sure about other options

-------- Original Message --------

**Comment by Nightenom** [comment]
We do this to get tooltip lines for items: [link to code](https://github.com/ldtteam/BlockUI/blob/version/main/src/main/java/com/ldtteam/blockui/controls/ItemIcon.java#L134), since this method provides no finer control, it would require for other mods to setup weak dependency. However it might be possible on our end to have toggleable limited tooltips (ie. such tooltips that will display block name and mod name only)

**Comment by Nightenom** [comment]
@SomewhatDamaged can we get info on whether this is resolved or not?

**Comment by SomewhatDamaged** [comment]
Sorry, yeah. It has been closed on PMMO issue tracker. I forgot to close here too.

https://github.com/Caltinor/Project-MMO-2.0/issues/324#issuecomment-1663682421
