### ISSUE TITLE
Improvement: Switchview should only trigger updates in it's currently active page, not all of them

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/BlockUI#45]
SwitchView doesn't currently implement `onUpdate`, which mean it falls back to the `View.onUpdate`, which in term updates very child.

In a SwitchView however, only one of the children can be shown at a time, meaning it's not really necessary to actively keep updating the other pages as well.

**Comment by Nightenom** [comment]
Closed in 4f2a142
