### ISSUE TITLE
Support "empty texts" in scrolling lists

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/BlockUI#84]
When a list has no items in it, you usually have some supporting text stating "This list is empty" to have at least something present on your screen.

Could the scrolling list support an `emptytext` attribute that works similar to any text source.
When the data provider of the list has no items in it, it will render a single text element with the given `emptytext`, when there are items in the data provider, the items are rendered instead.

**Comment by Nightenom** [comment]
can be PRed as empty_text + empty_color + empty_scale as list "extension" if u wanna

**Comment by Nightenom** [comment]
Closed in #85 #86
